#
# ansible-playbook read host.yml
#
---
- hosts: all
  gather_facts: no 

  tasks:

    - name: print ouput on screen
      shell: hostname -f
      register: v_out
      ignore_errors: true

    - debug: msg="Resultat v_out={{ v_out }}"